export const GENRE_LIST_REQUEST = "GENRE_LIST_REQUEST";
export const GENRE_LIST_SUCCESS = "GENRE_LIST_SUCCESS";
export const GENRE_LIST_FAIL = "GENRE_LIST_FAIL";

export const GENRE_CREATE_REQUEST = "GENRE_CREATE_REQUEST";
export const GENRE_CREATE_SUCCESS = "GENRE_CREATE_SUCCESS";
export const GENRE_CREATE_FAIL = "GENRE_CREATE_FAIL";

export const GENRE_DELETE_REQUEST = "GENRE_DELETE_REQUEST";
export const GENRE_DELETE_SUCCESS = "GENRE_DELETE_SUCCESS";
export const GENRE_DELETE_FAIL = "GENRE_DELETE_FAIL";
